In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
a=pd.read_csv('/train.csv')
x=a.drop("price_range",axis=1)
y= a["price_range"]
print(x)
print(y)
scaler=MinMaxScaler()
scaler.fit(x)
x_scaled=scaler.transform(x)
print(x_scaled)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7
1       0.7        136        3   6        905      1988  2631    17     3
2       0.9        145        5   6       1263      1716  2603    11     2
3       0.8        131        6   9       1216      1786  2769    16     8
4       0.6        141        2  14       1208      1212  1411     8     2
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
1995    0.8        106        6  14       1222      1890   668    13     4
1996    0.2        187        4   3        915      1965  2032    11    10
1997    0.7        108        8   3        868      1632  3057     9     1
1998    0.1        145        5   5        336       670   869    18    10
1999    0.9        168        6  16        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi
0            19        0             0     1
1             7        1             1     0
2             9        1             1     0
3            11        1             0     0
4            15        1             1     0
...         ...      ...           ...   ...
1995         19        1             1     0
1996         16        1             1     1
1997          5        1             1     0
1998         19        1             1     1
1999          2        1             1     1

[2000 rows x 20 columns]
0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64
[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]

In [ ]:
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.30)
print(x_train.shape)
print(x_train)
print(y_train.shape)
print(y_train)
print(x_test.shape)
print(x_test)
print(y_test.shape)
print(y_test)

(212, 13)
     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
112   64    0   2       140   313    0        1      133      0      0.2
238   77    1   0       125   304    0        0      162      1      0.0
299   45    1   3       110   264    0        1      132      0      1.2
26    59    1   2       150   212    1        1      157      0      1.6
203   68    1   2       180   274    1        0      150      1      1.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
111   57    1   2       150   126    1        1      173      0      0.2
52    62    1   2       130   231    0        1      146      0      1.8
301   57    1   0       130   131    0        1      115      1      1.2
128   52    0   2       136   196    0        0      169      0      0.1
208   49    1   2       120   188    0        1      139      0      2.0

     slope  ca  thal
112      2   0     3
238      2   3     2
299      1   0     3
26       2   0     2
203      1   0     3
..     ...  ..   ...
111      2   1     3
52       1   3     3
301      1   1     3
128      1   0     2
208      1   3     3

[212 rows x 13 columns]
(91, 13)
     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
40    51    0   2       140   308    0        0      142      0      1.5
201   60    1   0       125   258    0        0      141      1      2.8
168   63    1   0       130   254    0        0      147      0      1.4
183   58    1   2       112   230    0        0      165      0      2.5
151   71    0   0       112   149    0        1      125      0      1.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
29    53    1   2       130   197    1        0      152      0      1.2
27    51    1   2       110   175    0        1      123      0      0.6
44    39    1   2       140   321    0        0      182      0      0.0
200   44    1   0       110   197    0        0      177      0      0.0
204   62    0   0       160   164    0        0      145      0      6.2

     slope  ca  thal
40       2   1     2
201      1   1     3
168      1   1     3
183      1   1     3
151      1   0     2
..     ...  ..   ...
29       0   0     2
27       2   0     2
44       2   0     2
200      2   1     2
204      0   3     3

[91 rows x 13 columns]
(212,)
112    1
238    0
299    0
26     1
203    0
      ..
111    1
52     1
301    0
128    1
208    0
Name: target, Length: 212, dtype: int64
(91,)
40     1
201    0
168    0
183    0
151    1
      ..
29     1
27     1
44     1
200    0
204    0
Name: target, Length: 91, dtype: int64

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
a=pd.read_csv('/content/heart.csv')
x=a.drop("target",axis=1)
y= a["target"]
print(x)
print(y)
scaler=MinMaxScaler()
scaler.fit(x)
x_scaled=scaler.transform(x)
print(x_scaled)
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.30)
print(x_train.shape)
print(x_train)
print(y_train.shape)
print(y_train)
print(x_test.shape)
print(x_test)
print(y_test.shape)
print(y_test)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]
0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64
[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]
(212, 13)
     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
241   59    0   0       174   249    0        1      143      1      0.0
1     37    1   2       130   250    0        1      187      0      3.5
90    48    1   2       124   255    1        1      175      0      0.0
66    51    1   2       100   222    0        1      143      1      1.2
281   52    1   0       128   204    1        1      156      1      1.0
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
270   46    1   0       120   249    0        0      144      0      0.8
283   40    1   0       152   223    0        1      181      0      0.0
71    51    1   2        94   227    0        1      154      1      0.0
18    43    1   0       150   247    0        1      171      0      1.5
242   64    1   0       145   212    0        0      132      0      2.0

     slope  ca  thal
241      1   0     2
1        0   0     2
90       2   2     2
66       1   0     2
281      1   0     0
..     ...  ..   ...
270      2   0     3
283      2   0     3
71       2   1     3
18       2   0     2
242      1   2     1

[212 rows x 13 columns]
(91, 13)
     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
130   54    0   2       160   201    0        1      163      0      0.0
275   52    1   0       125   212    0        1      168      0      1.0
32    44    1   1       130   219    0        0      188      0      0.0
54    63    0   2       135   252    0        0      172      0      0.0
102   63    0   1       140   195    0        1      179      0      0.0
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
126   47    1   0       112   204    0        1      143      0      0.1
208   49    1   2       120   188    0        1      139      0      2.0
226   62    1   1       120   281    0        0      103      0      1.4
48    53    0   2       128   216    0        0      115      0      0.0
221   55    1   0       140   217    0        1      111      1      5.6

     slope  ca  thal
130      2   1     2
275      2   2     3
32       2   0     2
54       2   0     2
102      2   2     2
..     ...  ..   ...
126      2   0     2
208      1   3     3
226      1   1     3
48       2   0     0
221      0   0     3

[91 rows x 13 columns]
(212,)
241    0
1      1
90     1
66     1
281    0
      ..
270    0
283    0
71     1
18     1
242    0
Name: target, Length: 212, dtype: int64
(91,)
130    1
275    0
32     1
54     1
102    1
      ..
126    1
208    0
226    0
48     1
221    0
Name: target, Length: 91, dtype: int64

In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import random as rd
a=pd.read_csv('/content/heart.csv')
x=a.drop("target",axis=1)
y=a["target"]
scaler=MinMaxScaler()
scaler.fit(x)
x_scaled=scaler.transform(x)
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42)
f=x_train.shape[1]
w=[]
for _ in range(f):
    weight=rd.random()
    w.append(weight)
bias=rd.random()
def perceptron(x):
    z = (
        x[0]*w[0]+
        x[1]*w[1]+
        x[2]*w[2]+
        x[3]*w[3]+
        x[4]*w[4]+
        x[5]*w[5]+
        x[6]*w[6]+
        x[7]*w[7]+
        x[8]*w[8]+
        x[9]*w[9]+
        x[10]*w[10]+
        x[11]*w[11]+
        x[12]*w[12]+
        bias
    )
    return 1/(1+np.exp(-z))
y_p=[]
for x in x_train:
    if perceptron(x)>=0.5:
        y_p.append(1)
    else:
        y_p.append(0)

c_p=np.sum(y_p==y_train)
total=len(y_train)
acc=c_p / total
print(f'Accuracy:{acc:.2f}')

Accuracy:0.55